#!/usr/bin/env python3
# _ai-memory/skills/aim-best-practices-researcher/scripts/bp_index.py
"""Regenerate-from-disk INDEX for best-practices (BP-*.md) files.

The best-practices INDEX is rebuilt by scanning ``BP-*.md`` on disk and
rendering a canonical table sorted by BP-ID. This is idempotent — running it
twice on the same directory yields byte-identical output — so it replaces any
append-only maintenance that could duplicate or drift rows (AIM-010 / #292).

Modes (mutually exclusive):
  --write  Rebuild INDEX.md from the BP-*.md files on disk, then report.
  --check  Fire-only-if-missing: silent on the happy path (every BP file has an
           INDEX row); prints offenders to stderr and exits non-zero when a BP
           file has no INDEX row (or INDEX.md is absent while BP files exist).

Usage:
    bp_index.py --write  oversight/knowledge/best-practices
    bp_index.py --check  oversight/knowledge/best-practices
"""

import argparse
import re
import sys
from pathlib import Path

INDEX_NAME = "INDEX.md"
BP_GLOB = "BP-*.md"

# Filename form: BP-<digits>-<slug>.md  (slug optional)
_BP_FILE_RE = re.compile(r"^BP-(\d+)(?:-(.*))?\.md$")
# First markdown H1 in a BP file.
_H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
# "**Date**: YYYY-MM-DD" metadata line.
_DATE_RE = re.compile(r"^\*\*Date\*\*:\s*(\d{4}-\d{2}-\d{2})", re.MULTILINE)
# A BP filename referenced anywhere in an existing INDEX (for --check).
_INDEX_REF_RE = re.compile(r"BP-\d+(?:-[^\s|)/]*)?\.md")

_GENERATED_MARKER = "<!-- GENERATED by bp_index.py"


class BPFile:
    """A parsed BP-*.md file: numeric id, display title, optional date."""

    def __init__(self, path: Path, numeric_id: int, title: str, date: str | None):
        self.path = path
        self.numeric_id = numeric_id
        self.title = title
        self.date = date

    @property
    def display_id(self) -> str:
        return f"BP-{self.numeric_id:03d}"


def _table_cell(s: str) -> str:
    """Escape pipe characters so a value can't break the markdown table."""
    return s.replace("|", "\\|")


def _title_for(filename_slug: str | None, body: str) -> str:
    """Derive a display title: first H1 (minus a 'Research Report:' prefix),
    falling back to the humanized filename slug, then an empty string."""
    m = _H1_RE.search(body)
    if m:
        title = m.group(1).strip()
        title = re.sub(r"^Research Report:\s*", "", title, flags=re.IGNORECASE)
        if title:
            return title
    if filename_slug:
        return filename_slug.replace("-", " ").strip()
    return ""


def scan_bp_files(bp_dir: Path) -> list[BPFile]:
    """Scan a directory for BP-*.md files, sorted by numeric BP-ID ascending."""
    found: list[BPFile] = []
    for path in bp_dir.glob(BP_GLOB):
        if not path.is_file():
            continue
        m = _BP_FILE_RE.match(path.name)
        if not m:
            continue
        numeric_id = int(m.group(1))
        slug = m.group(2)
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            body = ""
        date_m = _DATE_RE.search(body)
        found.append(
            BPFile(
                path=path,
                numeric_id=numeric_id,
                title=_title_for(slug, body),
                date=date_m.group(1) if date_m else None,
            )
        )
    found.sort(key=lambda b: b.numeric_id)
    return found


def render_index(bp_files: list[BPFile], script_hint: str) -> str:
    """Render the full text of INDEX.md from the scanned BP files."""
    lines = [
        "# Best Practices Index",
        "",
        f"{_GENERATED_MARKER} — do not edit by hand.",
        f"     Regenerate: python3 {script_hint} --write <this-dir> -->",
        "",
    ]
    if not bp_files:
        lines.append("_No best practices recorded yet._")
        lines.append("")
        return "\n".join(lines)

    lines.append("| BP | Topic | Date | File |")
    lines.append("|----|-------|------|------|")
    for b in bp_files:
        lines.append(
            f"| {b.display_id} | {_table_cell(b.title)} | "
            f"{b.date or '—'} | {_table_cell(b.path.name)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _indexed_filenames(index_path: Path) -> set[str]:
    """Return the set of BP filenames referenced in an existing INDEX.md."""
    if not index_path.is_file():
        return set()
    try:
        text = index_path.read_text(encoding="utf-8")
    except OSError:
        return set()
    return set(_INDEX_REF_RE.findall(text))


def cmd_write(bp_dir: Path, index_path: Path, script_hint: str) -> int:
    bp_files = scan_bp_files(bp_dir)
    index_path.write_text(render_index(bp_files, script_hint), encoding="utf-8")
    print(
        f"INDEX regenerated: {len(bp_files)} best practice(s) -> {index_path}",
        file=sys.stderr,
    )
    return 0


def cmd_check(bp_dir: Path, index_path: Path) -> int:
    bp_files = scan_bp_files(bp_dir)
    if not bp_files:
        # Nothing to index — silent happy path.
        return 0
    indexed = _indexed_filenames(index_path)
    missing = [b for b in bp_files if b.path.name not in indexed]
    if not missing:
        # Every BP file has an INDEX row — silent (fire-only-if-missing).
        return 0
    if not index_path.is_file():
        print(
            f"MISSING: {index_path} does not exist but "
            f"{len(bp_files)} BP file(s) are present — run --write.",
            file=sys.stderr,
        )
    else:
        print(
            f"MISSING: {len(missing)} best practice(s) have no INDEX row "
            "— run --write to regenerate:",
            file=sys.stderr,
        )
    for b in missing:
        print(f"  - {b.path.name}", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate the best-practices INDEX.md from disk (--write) or "
            "verify every BP-*.md has an INDEX row (--check)."
        )
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--write",
        action="store_true",
        help="Rebuild INDEX.md from BP-*.md on disk (idempotent).",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help=(
            "Silent when every BP file has an INDEX row; non-zero and lists "
            "offenders when any BP file is unindexed."
        ),
    )
    parser.add_argument(
        "bp_dir",
        metavar="BP_DIR",
        help="Directory holding BP-*.md and INDEX.md "
        "(e.g. oversight/knowledge/best-practices).",
    )
    args = parser.parse_args()

    bp_dir = Path(args.bp_dir)
    index_path = bp_dir / INDEX_NAME
    script_hint = f"{Path(__file__).name}"

    if not bp_dir.is_dir():
        # Non-fatal: nothing to do if the directory has not been scaffolded.
        print(f"NOTE: directory absent — nothing to index: {bp_dir}", file=sys.stderr)
        return 0

    if args.write:
        return cmd_write(bp_dir, index_path, script_hint)
    return cmd_check(bp_dir, index_path)


if __name__ == "__main__":
    sys.exit(main())
