#!/usr/bin/env python3
# _ai-memory/skills/aim-best-practices-researcher/scripts/bp_index.py
"""Update the best-practices INDEX for BP-*.md files.

``--write`` appends any BP-*.md files missing from the existing INDEX.md
table (matched by BP-ID) without touching already-present rows or any other
content in the file — it never regenerates a curated INDEX. If no INDEX.md
exists yet, a fresh one is generated from disk (bootstrap only).

Modes (mutually exclusive):
  --write  Append missing BP rows to an existing INDEX.md (idempotent,
           non-destructive); bootstrap a fresh INDEX.md if none exists yet.
  --check  Fire-only-if-missing: silent on the happy path (every BP file has an
           INDEX row, matched by BP-ID); prints offenders to stderr and exits
           non-zero when a BP file has no INDEX row (or INDEX.md is absent
           while BP files exist).

Usage:
    bp_index.py --write  oversight/knowledge/best-practices
    bp_index.py --check  oversight/knowledge/best-practices
"""

import argparse
import re
import sys
from pathlib import Path

INDEX_NAME = "INDEX.md"
BP_GLOB = "BP-*.md"

# Filename form: BP-<digits>-<slug>.md  (slug optional)
_BP_FILE_RE = re.compile(r"^BP-(\d+)(?:-(.*))?\.md$")
# First markdown H1 in a BP file.
_H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
# "**Date**: YYYY-MM-DD" metadata line.
_DATE_RE = re.compile(r"^\*\*Date\*\*:\s*(\d{4}-\d{2}-\d{2})", re.MULTILINE)
# A BP-ID in a table row's first cell, e.g. "BP-001" (id-keyed, not filename).
_ROW_ID_RE = re.compile(r"^BP-(\d+)$", re.IGNORECASE)
# A markdown table separator cell, e.g. "---", ":---", "---:", ":---:".
_SEP_CELL_RE = re.compile(r"^:?-+:?$")
# "Total findings: N" footer line (mechanical count, safe to bump on append).
_TOTAL_FINDINGS_RE = re.compile(r"(Total findings:\s*)(\d+)")

_GENERATED_MARKER = "<!-- GENERATED by bp_index.py"


class BPFile:
    """A parsed BP-*.md file: numeric id, display title, optional date."""

    def __init__(self, path: Path, numeric_id: int, title: str, date: str | None):
        self.path = path
        self.numeric_id = numeric_id
        self.title = title
        self.date = date

    @property
    def display_id(self) -> str:
        return f"BP-{self.numeric_id:03d}"


def _table_cell(s: str) -> str:
    """Escape pipe characters so a value can't break the markdown table."""
    return s.replace("|", "\\|")


def _title_for(filename_slug: str | None, body: str) -> str:
    """Derive a display title: first H1 (minus a 'Research Report:' prefix),
    falling back to the humanized filename slug, then an empty string."""
    m = _H1_RE.search(body)
    if m:
        title = m.group(1).strip()
        title = re.sub(r"^Research Report:\s*", "", title, flags=re.IGNORECASE)
        if title:
            return title
    if filename_slug:
        return filename_slug.replace("-", " ").strip()
    return ""


def scan_bp_files(bp_dir: Path) -> list[BPFile]:
    """Scan a directory for BP-*.md files, sorted by numeric BP-ID ascending."""
    found: list[BPFile] = []
    for path in bp_dir.glob(BP_GLOB):
        if not path.is_file():
            continue
        m = _BP_FILE_RE.match(path.name)
        if not m:
            continue
        numeric_id = int(m.group(1))
        slug = m.group(2)
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            body = ""
        date_m = _DATE_RE.search(body)
        found.append(
            BPFile(
                path=path,
                numeric_id=numeric_id,
                title=_title_for(slug, body),
                date=date_m.group(1) if date_m else None,
            )
        )
    found.sort(key=lambda b: b.numeric_id)
    return found


def render_index(bp_files: list[BPFile], script_hint: str) -> str:
    """Render the full text of INDEX.md from the scanned BP files."""
    lines = [
        "# Best Practices Index",
        "",
        f"{_GENERATED_MARKER} — do not edit by hand.",
        f"     Regenerate: python3 {script_hint} --write <this-dir> -->",
        "",
    ]
    if not bp_files:
        lines.append("_No best practices recorded yet._")
        lines.append("")
        return "\n".join(lines)

    lines.append("| BP | Topic | Date | File |")
    lines.append("|----|-------|------|------|")
    for b in bp_files:
        lines.append(
            f"| {b.display_id} | {_table_cell(b.title)} | "
            f"{b.date or '—'} | {_table_cell(b.path.name)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _split_row_cells(line: str) -> list[str]:
    """Split a markdown table row into trimmed cell strings, dropping the
    empty leading/trailing cells produced by a row's outer pipes."""
    parts = line.strip().split("|")
    if parts and parts[0] == "":
        parts = parts[1:]
    if parts and parts[-1] == "":
        parts = parts[:-1]
    return [p.strip() for p in parts]


def _is_separator_row(cells: list[str]) -> bool:
    return bool(cells) and all(_SEP_CELL_RE.match(c) for c in cells)


def _looks_like_bp_header(cells: list[str]) -> bool:
    return bool(cells) and cells[0].strip().lower() in ("bp-id", "bp id", "bp")


def _row_ids(lines: list[str]) -> set[str]:
    """Return every BP-ID found in a table row's first cell, across all
    tables in ``lines`` (id-keyed — immune to BP-IDs mentioned in prose)."""
    ids: set[str] = set()
    for line in lines:
        if not line.strip().startswith("|"):
            continue
        cells = _split_row_cells(line)
        if not cells:
            continue
        m = _ROW_ID_RE.match(cells[0])
        if m:
            ids.add(f"BP-{int(m.group(1)):03d}")
    return ids


def _find_bp_table(lines: list[str]):
    """Locate the best-practices table (header cell 0 looks like a BP-ID
    column, followed by a valid separator row). Returns
    ``(header_cells, last_row_idx, existing_ids)`` or ``None`` if no such
    table is present.

    Only the first such table is treated as canonical (a second BP-ID-headed
    table, e.g. an "Archived" section, is not merged into membership — a
    documented limitation, not fixed here)."""
    i = 0
    while i < len(lines) - 1:
        line = lines[i]
        if line.strip().startswith("|"):
            header_cells = _split_row_cells(line)
            sep_cells = _split_row_cells(lines[i + 1])
            if _is_separator_row(sep_cells) and _looks_like_bp_header(header_cells):
                last_row_idx = i + 1
                j = i + 2
                # Sweep the whole contiguous pipe block (no blank line
                # breaks it) without stopping at a non-BP-ID row — a
                # divider/note/spacer row *inside* the table must not
                # truncate the scan before later real BP rows. last_row_idx
                # only advances on an actual BP-ID row, so a table butted
                # directly against this one with no blank line — e.g. a
                # Status Legend table — is still never counted as more BP
                # rows or included in the splice bound.
                while j < len(lines) and lines[j].strip().startswith("|"):
                    cells = _split_row_cells(lines[j])
                    if cells and _ROW_ID_RE.match(cells[0]):
                        last_row_idx = j
                    j += 1
                existing_ids = _row_ids(lines[i + 2 : j])
                return header_cells, last_row_idx, existing_ids
        i += 1
    return None


def _render_row(header_cells: list[str], b: BPFile) -> str:
    """Render a new table row matching an existing table's column layout.
    Derivable columns (BP-ID, Topic, File, a verification date) are filled
    in; anything else (e.g. curated-only Status/Confidence) gets the literal
    placeholder ``TBD`` — greppable, and can't be mistaken for a real
    curated value (unlike e.g. reusing a legend value such as NEEDS_REVIEW)."""
    cells = []
    for name in header_cells:
        key = name.strip().lower()
        if key in ("bp-id", "bp id", "bp", "id"):
            cells.append(b.display_id)
        elif key in ("topic", "title"):
            cells.append(_table_cell(b.title))
        elif key == "file":
            cells.append(_table_cell(b.path.name))
        elif "date" in key or "verified" in key:
            cells.append(b.date or "TBD")
        else:
            cells.append("TBD")
    return "| " + " | ".join(cells) + " |"


def _bump_total_findings(text: str, new_total: int) -> str:
    """Update a '*Total findings: N*' footer to the post-append count. A
    no-op if the line isn't present. Mechanical count only — the human
    '*Last updated*' verification date is never touched by an append."""
    return _TOTAL_FINDINGS_RE.sub(rf"\g<1>{new_total}", text, count=1)


def _write_append(bp_files: list[BPFile], index_path: Path) -> int:
    """Append BP files missing (by BP-ID) from an existing INDEX.md, leaving
    every existing row and all surrounding content byte-for-byte untouched.

    Limitation: read_text()/write_text() use Python's universal-newline
    handling, so any CRLF in the source file is normalized to LF on write.
    Not preserved on purpose — this repo is LF-only."""
    text = index_path.read_text(encoding="utf-8")
    lines = text.split("\n")
    table = _find_bp_table(lines)

    if table is None:
        if not bp_files:
            print(
                f"NOTE: {index_path} has no BP-ID table and no BP files "
                "are present — nothing to do.",
                file=sys.stderr,
            )
            return 0
        print(
            f"ERROR: {index_path} exists but no BP-ID table could be "
            "parsed — refusing to overwrite curated content. Fix the table "
            "by hand, or remove the file to bootstrap a fresh INDEX.",
            file=sys.stderr,
        )
        return 1

    header_cells, last_row_idx, existing_ids = table
    missing = [b for b in bp_files if b.display_id not in existing_ids]
    if not missing:
        print(
            f"INDEX up to date: {len(bp_files)} best practice(s), 0 "
            f"appended -> {index_path}",
            file=sys.stderr,
        )
        return 0

    new_rows = [_render_row(header_cells, b) for b in missing]
    spliced = lines[: last_row_idx + 1] + new_rows + lines[last_row_idx + 1 :]
    out_text = _bump_total_findings(
        "\n".join(spliced), len(existing_ids) + len(missing)
    )
    index_path.write_text(out_text, encoding="utf-8")
    print(
        f"INDEX appended: {len(missing)} new best practice(s), "
        f"{len(existing_ids)} preserved -> {index_path}",
        file=sys.stderr,
    )
    return 0


def cmd_write(bp_dir: Path, index_path: Path, script_hint: str) -> int:
    bp_files = scan_bp_files(bp_dir)

    if not index_path.is_file():
        # Bootstrap: nothing curated exists yet to protect.
        index_path.write_text(render_index(bp_files, script_hint), encoding="utf-8")
        print(
            f"INDEX regenerated: {len(bp_files)} best practice(s) -> {index_path}",
            file=sys.stderr,
        )
        return 0

    return _write_append(bp_files, index_path)


def cmd_check(bp_dir: Path, index_path: Path) -> int:
    bp_files = scan_bp_files(bp_dir)
    if not bp_files:
        # Nothing to index — silent happy path.
        return 0
    if not index_path.is_file():
        print(
            f"MISSING: {index_path} does not exist but "
            f"{len(bp_files)} BP file(s) are present — run --write.",
            file=sys.stderr,
        )
        for b in bp_files:
            print(f"  - {b.path.name}", file=sys.stderr)
        return 1
    # Scoped to the canonical BP table (same table --write appends to), not
    # whole-document _row_ids — otherwise a BP-ID first-cell in any other
    # pipe-table would falsely mask a genuinely-missing canonical row. No
    # canonical table found -> empty membership (fail-safe: everything
    # reports missing, mirroring _write_append's refusal in that case).
    table = _find_bp_table(index_path.read_text(encoding="utf-8").split("\n"))
    indexed = table[2] if table else set()
    missing = [b for b in bp_files if b.display_id not in indexed]
    if not missing:
        # Every BP file has a matching BP-ID row — silent (fire-only-if-missing).
        return 0
    print(
        f"MISSING: {len(missing)} best practice(s) have no INDEX row "
        "— run --write to regenerate:",
        file=sys.stderr,
    )
    for b in missing:
        print(f"  - {b.path.name}", file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Append missing BP-*.md rows to the best-practices INDEX.md "
            "(--write) or verify every BP-*.md has a matching BP-ID row "
            "(--check)."
        )
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--write",
        action="store_true",
        help=(
            "Append missing BP-*.md rows to INDEX.md (idempotent, "
            "non-destructive); bootstrap a fresh INDEX.md if none exists."
        ),
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help=(
            "Silent when every BP file has an INDEX row; non-zero and lists "
            "offenders when any BP file is unindexed."
        ),
    )
    parser.add_argument(
        "bp_dir",
        metavar="BP_DIR",
        help="Directory holding BP-*.md and INDEX.md "
        "(e.g. oversight/knowledge/best-practices).",
    )
    args = parser.parse_args()

    bp_dir = Path(args.bp_dir)
    index_path = bp_dir / INDEX_NAME
    script_hint = f"{Path(__file__).name}"

    if not bp_dir.is_dir():
        # Non-fatal: nothing to do if the directory has not been scaffolded.
        print(f"NOTE: directory absent — nothing to index: {bp_dir}", file=sys.stderr)
        return 0

    if args.write:
        return cmd_write(bp_dir, index_path, script_hint)
    return cmd_check(bp_dir, index_path)


if __name__ == "__main__":
    sys.exit(main())
