"""Integration tests for BUG-287: live container read-only key acceptance + write rejection.

BUG-287 root cause: docker-compose.yml exposed only QDRANT__SERVICE__API_KEY to the
Qdrant container; the read-only key was generated by install.sh (R2.7 in
configure_environment) and consumed by the Python layer (MemoryConfig.qdrant_read_only_api_key
field + get_qdrant_client read_only branch) but never wired into the container's
environment block. Result: every get_qdrant_client(read_only=True) call produced HTTP 401.

Test 2 (test_qdrant_read_only_key_accepted_by_container): live container probe — skips
when QDRANT_READ_ONLY_API_KEY is absent or Qdrant is not reachable. Asserts HTTP 200 on
GET /collections with the read-only key, HTTP 401 with an invalid key (auth is active,
not open), and HTTP 403 on a write (PUT) attempt with the read-only key (write rejection —
the defining property of a read-only key). BUG-287 fix-r2: write-rejection probe added
per bug-doc verification step 4 (M-3 fix).

Test 3 (test_qdrant_read_only_key_python_consumer): end-to-end probe via
get_qdrant_client(read_only=True) — skips when QDRANT_READ_ONLY_API_KEY is absent or
Qdrant is not reachable. Exercises the documented Python entry point that was the
original failure site in the BUG-287 report (M-4 fix).

The pure YAML-parse test (no Docker dependency) was relocated to
tests/test_compose_qdrant_wiring.py so it runs in the unit CI tier without
--run-integration (BUG-287 fix-r2, H-1 fix).

References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client read_only
parameter implementation and MemoryConfig field).
"""

import contextlib
import os

import httpx
import pytest

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_QDRANT_BASE_URL = os.environ.get("QDRANT_URL", "http://localhost:26350")


def _qdrant_reachable() -> bool:
    """Return True if the Qdrant readiness endpoint responds with HTTP 200.

    Uses /readyz which is auth-whitelisted since Qdrant v1.5.0 (BP-145).
    Catches the full httpx.RequestError hierarchy and HTTPStatusError so that
    any connectivity failure triggers a skip rather than a test error — L-12 fix.
    """
    try:
        r = httpx.get(f"{_QDRANT_BASE_URL}/readyz", timeout=3.0)
        return r.status_code == 200
    except (httpx.RequestError, httpx.HTTPStatusError):
        return False


# ---------------------------------------------------------------------------
# Test 2: live container probe (integration, marker-gated)
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_qdrant_read_only_key_accepted_by_container() -> None:
    """Probe live Qdrant container; assert read-only key accepted for reads and
    rejected for writes (write rejection proves key is truly read-only).

    Skips when QDRANT_READ_ONLY_API_KEY env var is absent or empty (not yet deployed
    or running in an environment without .env.secrets loaded).
    Skips when no live Qdrant container is reachable at QDRANT_URL (default
    http://localhost:26350).

    Asserts:
    - GET /collections with read-only key returns HTTP 200 (key is valid + authorized)
    - GET /collections with an invalid key returns HTTP 401 (auth is active, not open)
    - PUT /collections/{sentinel} with read-only key returns HTTP 403 (write rejection)

    Write-rejection probe uses a sentinel collection name and cleans up in a finally
    block via the primary key — best-effort, no assertion on cleanup.

    References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client read_only
    parameter and MemoryConfig.qdrant_read_only_api_key field).
    Bug-doc verification step 4: PUT with read-only key must return 403 (M-3 fix).
    """
    read_only_key = os.environ.get("QDRANT_READ_ONLY_API_KEY", "").strip()
    if not read_only_key:
        pytest.skip("QDRANT_READ_ONLY_API_KEY not set — skipping live container probe")

    if not _qdrant_reachable():
        pytest.skip(
            f"Qdrant not reachable at {_QDRANT_BASE_URL}/readyz — "
            "skipping live container probe"
        )

    # Read-only key must be accepted for read operations
    r_valid = httpx.get(
        f"{_QDRANT_BASE_URL}/collections",
        headers={"api-key": read_only_key},
        timeout=5.0,
    )
    assert r_valid.status_code == 200, (
        f"BUG-287 regression: GET /collections with read-only key returned "
        f"HTTP {r_valid.status_code}, expected 200. "
        "Check that QDRANT__SERVICE__READ_ONLY_API_KEY is wired in docker-compose.yml "
        "and the container was restarted after the compose change."
    )

    # Invalid key must be rejected — confirms auth is active (not open / no-auth mode)
    r_invalid = httpx.get(
        f"{_QDRANT_BASE_URL}/collections",
        headers={"api-key": "invalid-key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
        timeout=5.0,
    )
    assert r_invalid.status_code == 401, (
        f"Unexpected HTTP {r_invalid.status_code} from Qdrant with an invalid key — "
        "expected 401. Qdrant may be running without API key auth enabled."
    )

    # Write-rejection probe: read-only key must be rejected for write operations (M-3 fix)
    sentinel = "bug287-readonly-probe"
    try:
        put_resp = httpx.put(
            f"{_QDRANT_BASE_URL}/collections/{sentinel}",
            headers={"api-key": read_only_key},
            json={"vectors": {"size": 4, "distance": "Cosine"}},
            timeout=5.0,
        )
        assert put_resp.status_code == 403, (
            f"Expected HTTP 403 on PUT /collections/{sentinel} with read-only key "
            f"(write rejection); got {put_resp.status_code}. "
            "The read-only key should permit reads but reject writes."
        )
    finally:
        # Best-effort cleanup: DELETE the sentinel collection with the primary key.
        # No assertion — sentinel may not exist if PUT was rejected at the auth layer.
        primary_key = os.environ.get("QDRANT_API_KEY", "")
        if primary_key:
            with contextlib.suppress(Exception):
                httpx.delete(
                    f"{_QDRANT_BASE_URL}/collections/{sentinel}",
                    headers={"api-key": primary_key},
                    timeout=5.0,
                )


# ---------------------------------------------------------------------------
# Test 3: Python consumer probe (integration, marker-gated)
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_qdrant_read_only_key_python_consumer() -> None:
    """End-to-end probe: get_qdrant_client(read_only=True) succeeds on a live container.

    Resolves BUG-287 fix-r2 finding M-4: the original Test 2 calls raw httpx and never
    exercises the documented Python entry point named in the BUG-287 commit message body.
    This test validates the full bidirectional loop: the Python key-swap branch must
    select the read-only key AND Qdrant must accept it.

    Skips when QDRANT_READ_ONLY_API_KEY env var is absent or empty.
    Skips when no live Qdrant container is reachable at QDRANT_URL.

    References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client read_only
    parameter and MemoryConfig.qdrant_read_only_api_key field).
    """
    if not os.environ.get("QDRANT_READ_ONLY_API_KEY", "").strip():
        pytest.skip("QDRANT_READ_ONLY_API_KEY not set — skipping Python consumer probe")
    if not _qdrant_reachable():
        pytest.skip(
            f"Qdrant not reachable at {_QDRANT_BASE_URL} — "
            "skipping Python consumer probe"
        )

    from memory.config import MemoryConfig
    from memory.qdrant_client import get_qdrant_client

    config = MemoryConfig()
    client = get_qdrant_client(read_only=True, config=config)
    collections = client.get_collections()
    assert collections is not None, (
        "get_qdrant_client(read_only=True).get_collections() returned None — "
        "expected a CollectionsResponse object."
    )
