"""Regression tests for BUG-287: QDRANT__SERVICE__READ_ONLY_API_KEY compose wiring.

BUG-287 root cause: docker-compose.yml exposed only QDRANT__SERVICE__API_KEY to the
Qdrant container; the read-only key was generated by install.sh (R2.7 in
configure_environment) and consumed by the Python layer (MemoryConfig.qdrant_read_only_api_key
field + get_qdrant_client read_only branch) but never wired into the container's
environment block. Result: every get_qdrant_client(read_only=True) call produced HTTP 401.

Test 1 (test_compose_wires_read_only_api_key): pure YAML-parse — no Docker dependency,
runs in standard CI. Asserts the BUG-287 fix is present and the primary auth key wiring
(QDRANT__SERVICE__API_KEY) is not accidentally removed (regression guard for
get_qdrant_client default callers).

Test 2 (test_qdrant_read_only_key_accepted_by_container): live container probe — skips
when QDRANT_READ_ONLY_API_KEY is absent or Qdrant is not reachable. Asserts HTTP 200 on
GET /collections with the read-only key and HTTP 401 with an invalid key (confirms auth
is active, not open).

References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client read_only
parameter implementation and MemoryConfig field).
"""

import os
from pathlib import Path

import httpx
import pytest
import yaml

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_COMPOSE_PATH = Path(__file__).parent.parent.parent / "docker" / "docker-compose.yml"
_QDRANT_BASE_URL = os.environ.get("QDRANT_URL", "http://127.0.0.1:26350")


def _qdrant_reachable() -> bool:
    """Return True if the Qdrant readiness endpoint responds with HTTP 200.

    Uses /readyz which is auth-whitelisted since Qdrant v1.5.0 (BP-145).
    """
    try:
        r = httpx.get(f"{_QDRANT_BASE_URL}/readyz", timeout=3.0)
        return r.status_code == 200
    except (httpx.ConnectError, httpx.TimeoutException):
        return False


# ---------------------------------------------------------------------------
# Test 1: pure YAML-parse (no Docker dependency)
# ---------------------------------------------------------------------------


def test_compose_wires_read_only_api_key() -> None:
    """Verify docker-compose.yml qdrant environment block contains read-only key wiring.

    Pure YAML-parse test — no Docker dependency, runs in standard CI. Asserts:
    - QDRANT__SERVICE__READ_ONLY_API_KEY is wired (BUG-287 fix present)
    - QDRANT__SERVICE__API_KEY is still wired (regression guard for default callers)

    References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client
    read_only parameter and MemoryConfig.qdrant_read_only_api_key field).
    """
    assert _COMPOSE_PATH.exists(), f"compose file not found at {_COMPOSE_PATH}"

    with _COMPOSE_PATH.open() as fh:
        compose = yaml.safe_load(fh)

    env_block = compose["services"]["qdrant"]["environment"]
    assert isinstance(env_block, list), "qdrant environment block must be a list"

    # BUG-287 fix: read-only key must be wired to container
    assert (
        "QDRANT__SERVICE__READ_ONLY_API_KEY=${QDRANT_READ_ONLY_API_KEY}" in env_block
    ), (
        "BUG-287 regression: QDRANT__SERVICE__READ_ONLY_API_KEY not found in qdrant "
        "service environment block. The read-only key must be wired so that "
        "get_qdrant_client(read_only=True) callers work end-to-end."
    )

    # Regression guard: primary auth key must still be present
    assert "QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}" in env_block, (
        "Regression: QDRANT__SERVICE__API_KEY was accidentally removed from qdrant "
        "service environment block. Default get_qdrant_client callers would break."
    )


# ---------------------------------------------------------------------------
# Test 2: live container probe (integration, marker-gated)
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_qdrant_read_only_key_accepted_by_container() -> None:
    """Probe live Qdrant container; assert read-only key accepted on GET /collections.

    Skips when QDRANT_READ_ONLY_API_KEY env var is absent or empty (not yet deployed
    or running in an environment without .env.secrets loaded).
    Skips when no live Qdrant container is reachable at QDRANT_URL (default
    http://127.0.0.1:26350).

    Asserts:
    - GET /collections with read-only key returns HTTP 200 (key is valid + authorized)
    - GET /collections with an invalid key returns HTTP 401 (auth is active, not open)

    Note: write-rejection probe (PUT → 403) is omitted per BUG-287 fix scope decision;
    the auth-active assertion (invalid key → 401) is sufficient for this regression test.

    References: BUG-287 (server-side wiring gap), TD-333 (get_qdrant_client read_only
    parameter and MemoryConfig.qdrant_read_only_api_key field).
    """
    read_only_key = os.environ.get("QDRANT_READ_ONLY_API_KEY", "").strip()
    if not read_only_key:
        pytest.skip("QDRANT_READ_ONLY_API_KEY not set — skipping live container probe")

    if not _qdrant_reachable():
        pytest.skip(
            f"Qdrant not reachable at {_QDRANT_BASE_URL}/readyz — "
            "skipping live container probe"
        )

    # Read-only key must be accepted for read operations
    r_valid = httpx.get(
        f"{_QDRANT_BASE_URL}/collections",
        headers={"api-key": read_only_key},
        timeout=5.0,
    )
    assert r_valid.status_code == 200, (
        f"BUG-287 regression: GET /collections with read-only key returned "
        f"HTTP {r_valid.status_code}, expected 200. "
        "Check that QDRANT__SERVICE__READ_ONLY_API_KEY is wired in docker-compose.yml "
        "and the container was restarted after the compose change."
    )

    # Invalid key must be rejected — confirms auth is active (not open / no-auth mode)
    r_invalid = httpx.get(
        f"{_QDRANT_BASE_URL}/collections",
        headers={"api-key": "invalid-key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
        timeout=5.0,
    )
    assert r_invalid.status_code == 401, (
        f"Unexpected HTTP {r_invalid.status_code} from Qdrant with an invalid key — "
        "expected 401. Qdrant may be running without API key auth enabled."
    )
