#!/usr/bin/env bash
# gen_known_template_versions.sh — regenerate the prior-shipped-template registry.
#
# Walks the git history of every file under templates/oversight/ and records the
# SHA-256 of each historical version's *content* (matching the installer's
# _sha256_file). The installer uses this registry to distinguish a stale
# old-shipped template copy (safe to auto-migrate) from a genuinely
# user-modified one (must be warned, never clobbered).
#
# Output: templates/known-oversight-template-versions.txt
#   one "<rel_path>\t<sha256>" row per distinct historical version.
#
# Re-run whenever a shipped oversight template changes, then commit the result.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="$REPO_ROOT/templates/known-oversight-template-versions.txt"

cd "$REPO_ROOT"

{
    echo "# Prior-shipped oversight-template content hashes (SHA-256)."
    echo "# Generated by scripts/gen_known_template_versions.sh — do not hand-edit."
    echo "# Format: <rel_path><TAB><sha256>"
} > "$OUT_FILE"

# Every path ever tracked under templates/oversight/ (current + deleted-then-restored).
# tformat: (not format:) terminates every entry with a newline — format: omits the
# trailing newline, which makes `while read` silently drop the final record.
paths="$(git log --pretty=tformat: --name-only -- 'templates/oversight/*' \
    | grep -E '^templates/oversight/.+' | sort -u)"

while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    rel_path="${path#templates/oversight/}"
    # Each commit that touched this path → hash its content at that commit.
    while IFS= read -r commit; do
        [[ -n "$commit" ]] || continue
        hash="$(git show "$commit:$path" 2>/dev/null | sha256sum | awk '{print $1}')" || continue
        [[ -n "$hash" ]] && printf '%s\t%s\n' "$rel_path" "$hash"
    done < <(git log --pretty=tformat:'%H' -- "$path")
done <<< "$paths" | sort -u >> "$OUT_FILE"

echo "Wrote $(grep -c $'\t' "$OUT_FILE") version rows to $OUT_FILE"
